---
title: "Weekly check-in 6"
date: "2022-07-18"
---

Answer these questions and submit your responses on iCollege.

I *highly recommend* writing your responses in a separate document and copying/pasting the text into iCollege. It will be far easier for you if you write the responses right after completing the readings and watching the videos instead of waiting until you get around to putting them in iCollege—**you will forget your questions and insights if you don't.**

### Session 11: Institutions, power, and inequality

1. What were the **three (3)** most interesting or exciting things you learned from the session? Why?
2. What were the **three (3)** muddiest or unclear things from the session this week? What are you still wondering about?  

### Session 12: Market failures

1. What were the **three (3)** most interesting or exciting things you learned from the session? Why?
2. What were the **three (3)** muddiest or unclear things from the session this week? What are you still wondering about?  

### Problem set 5 review

- Did you review the problem set answer key and compare the answers with your work?
    - Yes, by myself
    - Yes, with others from the class
    - No
- Which problem set question was the most difficult?
- What questions do you still have?
