---
title: "Welcome to class!"
date: "2023-05-31T14:11"
categories: [getting started]
---

Hello everyone!

I’m Andrew Heiss, your professor for PMAP 8141 (Microeconomics for Public Policy) this summer, and I’m so excited for the class!

I have a few important announcements before class:

- Before class, I’d love to get to know each you a little first, so I’ve created a quick survey to fill out. I’ve sent you a link to it via e-mail. Please take it at your earliest convenience.

- The entire course is available at a special class website at <https://econs23.classes.andrewheiss.com/>. Bookmark this site—it'll be your best friend for the next semester. I only use iCollege for collecting your assignments, posting answer keys, and offering the two exams (since it's password protected). This website is the official source of dates and all other class information. Because it's not part of iCollege, you'll be able to reference it even after you graduate and lose access to GSU resources. You can even share it with others—it's just a website!

- **Please read the main explanatory pages at your earliest convenience.** The instructions and expectations for the class are divided across different pages, all accessible from the menu bar at the top of the site. Please read the main pages for the [syllabus](/syllabus.qmd), [schedule](/schedule.qmd), [content](/content/index.qmd), and [assignments](/assignment/index.qmd).

- If you look at the [syllabus page](/syllabus.qmd), you'll notice that there is only one physical textbook for the class (and it’s ≈$11). Everything else is free. There will occasionally be copyrighted PDFs of articles or chapters from other books—those are available on iCollege.

Quick background about me: I'm an assistant professor here at the Andrew Young School, where I've been teaching MPA/MPP microeconomics, program evaluation, and data visualization. I moved here from Utah in Fall 2019, where I was a visiting professor of public management at the Marriott School of Business at Brigham Young University (BYU). While at BYU, I taught microeconomics, statistics, and data visualization (basically the same stuff I’m teaching now). I finished my PhD in public policy and political science from Duke in 2017, and before then I finished my MPA in nonprofit management from BYU in 2012. When I'm not teaching, I research international nonprofits, dictatorships, and human rights—absolutely nothing related to economics `r emoji::emoji("shrug")`

When I’m not teaching or researching, I’m normally chilling at home with my 6 kids (see <https://www.heissatopia.com> for photos and hilarious stories).

Again, I’m really excited to get started next week. This summer should be a blast!
