---
title: "Interaction and success"
date: "2023-06-28T13:00"
categories: [advice]
references:
- id: Glazier:2016
  author:
    - family: Glazier
      given: Rebecca A.
  citation-key: Glazier:2016
  container-title: Journal of Political Science Education
  DOI: 10.1080/15512169.2016.1155994
  issue: '4'
  issued:
    - year: 2016
      month: 10
  page: 437-456
  title: Building Rapport to Improve Retention and Success in Online Classes
  type: article-journal
  volume: '12'
---

Since the pandemic started, I've been studying the research on online teaching to see how to make my online classes as successful as possible. One almost universal key to success I've found is that learning requires social interaction to be successful [@Glazier:2016]. In fact, one of the greatest predictors of success is whether students build relationships with their classmates and their professor.

This is true for **both** online classes and face-to-face classes! It's entirely possible to take a face-to-face class and have almost no social interaction. The worst, most useless class I ever took as an undergraduate was a required Intro to US History class that met twice a week for 2 hours in a massive auditorium with 900 (!!!) other students. It was awful and I learned nothing.

So, interact with me and your classmates! Don't lurk in silence in the shadows. (Don't overshare either and spam the #general channel in Slack, but in my experience there's little risk of that). *Do* reach out and talk to your classmates (and me!).

To that end, one of the best ways to get to know each other is to help each other. Ask questions on Slack. If you see someone's question there and you know how to help, answer! 

You can also work on exercises and projects in groups if you want. Use Webex or Zoom to share screens with each other during calls so you can see what you're doing. In the programming world, a common technique for working on code is [pair programming](https://en.wikipedia.org/wiki/Pair_programming), where two people work on the same script. If we were meeting in class, we'd do this with the math problems face-to-face, working during class in groups of 2–3 with me walking around and helping. **Feel free to replicate that experience** and work with others on the problem sets. It's not cheating! (As long as you don't turn in identical work)

Help make this semester fantastic by talking, reaching out, and otherwise socially interacting!

And remember, you can reach out to me at any time via Slack or e-mail or at [my Calendly page](https://calendly.com/andrewheiss/). I'm typically super responsive. **Do not suffer in silence!**
