---
title: "Exam 1 details"
date: "2023-06-28T11:24"
categories: [course details]
---

Hi everyone!

It's already time for the first exam! So fun!

The study guide for the exam is [at the course website](/resource/exam1.qmd). There are also some practice indifference curve/budget line questions [here too](/resource/practice-questions.qmd).

Exam 1 will be available online at iCollege from July 3–9. You can take it any time during that period. It closes at 11:59 PM on July 9, so make sure you finish it by then.

The exam has a mix of multiple choice and short and longer answer questions, and the questions are similar to what you've seen in past problem sets. 

Importantly, **the test is open-note, open-problem set, open-book, and open-internet, but it is *not* open-any other human being or online chatbot like ChatGPT.** Do not talk about the test with your classmates after you’ve taken it. 

You must complete this test in one sitting. You have a 5 hour window to take the exam, but *it will not take 5 hours, I promise*. It normally takes people 1–1.5 hours. 

The reason I have the window is to give you plenty of time to search your notes, textbook, etc., and not feel rushed. I’ve had a couple students take 5+ hours on this test, but it’s because they took a break and had long lunch and went on a walk and then came back to the test. That’s 100% fine. 

So you have a 5-hour window, but it **absolutely** will not take that long. And if you go over, it's okay—it'll let me know you went over, but it won't lock you out, and you won't be penalized for it. But also, really really really you shouldn't take that long! Don’t worry :) 

Good luck! And as always, remember that you can (and should!) reach out to me for help!
