---
title: "Pandemics, white supremacy, and public policy"
date: "2023-05-31T14:20"
categories: [getting started]
---

Hi everyone again,

This pandemic absolutely sucks, it's been compounded by the ongoing social movement against police violence and white supremacy (and a coup attempt in January 2021!). Please remember that *I will try my hardest this summer* to make whatever accommodations you need to continue learning. 

From the founding of this country, white people have devalued Black lives. The system of American capitalism is based on a foundation of racial conflict. We’ll talk about this throughout the semester, and [we have a session dedicated to the history of the notion of whiteness](https://econs23.classes.andrewheiss.com/content/13-content.html) and how it has (1) shaped the modern economy in favor of those who count as “white” and (2) enabled violence against those who do not fit those standards. Black lives matter, and economics and public policy have long ignored this.

The ongoing pandemic is a mess for everyone, but its effects are not equally borne due to structural and institutional racism and discrimination. Black communities, indigenous communities, and other people of color have been inordinately affected by health and economic effects of COVID-19. The unevenness of the vaccine rollout has mirrored the unevenness of the burden of the disease. Compounding all this, extrajudicial and police violence have continued and intensified.

As students of public policy and administration, you all have deep passion for the public sector. You are advocates, activists, organizers, and government officials. Given everything you do to address institutional racism and improve the public sector, I know that you are deeply impacted by both the pandemic and the ongoing protests against state violence.

If you want to talk with a professional, GSU offers online counseling and support through the university’s Counseling Center. Find more information at <https://counselingcenter.gsu.edu/services/counseling-services/individual-counseling/>

If you want to donate financially, these organizations could use support:

- [Black Lives Matter](https://blacklivesmatter.com/)
- [Atlanta Solidarity Fund](https://actionnetwork.org/fundraising/support-justiceforgeorgefloyd-protesters-in-atlanta)
- [NAACP Legal Defense Fund](https://www.naacpldf.org/)
- [Southern Poverty Law Center](https://www.splcenter.org/)

If you are a white person looking to educate yourself and your community about issues of racism and how you can learn more about anti-racism, abolitionism, and transformative justice, refer to these resources:

- *We Do This 'Til We Free Us* by Mariame Kaba
- *Me and White Supremacy* by Layla Saad
- *Between the World and Me* by Ta-Nehisi Coates
- [The Teaching Tolerance project](https://www.tolerance.org/professional-development/white-antiracism-living-the-legacy)

I am here for you, especially as we work to confront economic institutional racism and injustice.

Stay safe and healthy!
